config/routes.rb
Rails.application.routes.draw do
  get 'access/index'

 match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
 match 'auth/failure', to: redirect('/'), via: [:get, :post]
 match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :microposts

   root 'microposts#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :find_tweet, :only => [:edit, :destroy, :update, :show]
  before_action :user_signed_in!
  def index
    @micropost = current_user.microposts.build
    @microposts = Micropost.all.order("created_at DESC")
  end

  def show
  end

  def create
    @micropost = current_user.microposts.create!(tweet_params)

      respond_to do |format|

        format.html { redirect_to root_path }
        format.js {}
      end
  end

  def edit
  end

  def update
    if @micropost.update(tweet_params)
      redirect_to root_path
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|

      format.html { redirect_to root_path }
      format.js {}
    end
  end


 private
  def find_tweet
    @micropost = Micropost.find(params[:id])
  end

  def tweet_params
    params.require(:micropost).permit(:tweet)
  end


  def user_signed_in!
    if current_user.nil?
      redirect_to access_index_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="nav-links">
    <% if current_user %>
     Signed in as <strong> <%= current_user.name %> </strong>
    <%= link_to "logout", signout_path %>
    <% else %>
    <%= link_to "SignIn with Facebook", "/auth/facebook" %>
    <% end %>
  </div>
  <div id="wrapper">
 <%= yield %>
  </div>
</div>

</body>
</html>

app/views/microposts/_form.html.erb
<div id="tweet-box">
    <%= simple_form_for @micropost, remote: true do |m| %>
     <%= m.input :tweet %>
     <%= m.button :submit %>
    <% end %>
</div>

app/views/microposts/_micropost.html.erb
<div id="tweet_<%=micropost.id%>">
<h3> <%= micropost.tweet %> </h3>
  <div id="tweet-info">
     <p> <%= link_to "delete", micropost_path(micropost), method: :delete, remote: true %> </p>
     <p> <%= time_ago_in_words(micropost.created_at) %> ago </p>
  </div>
</div>

app/views/microposts/create.js.erb
$("<%= escape_javascript(render @micropost) %>").prependTo("#tweets");
$('#micropost_tweet').val(" ");
$('#tweet_<%= @micropost.id %>').hide().fadeIn(500);

app/views/microposts/destroy.js.erb
$('#tweet_<%= @micropost.id %>').fadeOut(500, function(){

  $(this).remove();

});

app/views/microposts/edit.html.erb
<%= render('form') %>

app/views/microposts/index.html.erb
<%= render('form') %>


<div id="tweets" class="tweets-container">
  <%= render(@microposts) %>
</div>

app/views/microposts/show.html.erb
<div class="tweet-show">
  <%= @micropost.tweet %>
  <%= time_ago_in_words(@micropost.created_at)%>
</div>